CREATE DATABASE IF NOT EXISTS solid_store
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE solid_store;

CREATE TABLE IF NOT EXISTS users (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    email VARCHAR(190) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    phone VARCHAR(20) NOT NULL,
    cpf VARCHAR(20) NULL,
    zip VARCHAR(12) NOT NULL,
    address VARCHAR(180) NOT NULL,
    address_number VARCHAR(30) NOT NULL,
    complement VARCHAR(120) NULL,
    neighborhood VARCHAR(120) NOT NULL,
    city VARCHAR(120) NOT NULL,
    newsletter TINYINT(1) NOT NULL DEFAULT 0,
    profile_image LONGTEXT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
